domains:
  api:
    algorithm: token_bucket
    capacity: 5
    refill_rate: 0.05
    refill_interval_ms: 1000
    identifier: ip

  payments:
    algorithm: token_bucket
    capacity: 20
    refill_rate: 2
    refill_interval_ms: 1000
    identifier: ip

  sms_gateway:
    algorithm: leaky_bucket
    capacity: 10
    drain_rate: 2
    drain_interval_ms: 1000
    identifier: ip
